services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: suasenhasegura
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço da API C# (.NET)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: csharp_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Sobrescreve a ConnectionString do appsettings.json
      - ConnectionStrings__DefaultConnection=Host=db;Database=meubanco;Username=postgres;Password=suasenhasegura
    depends_on:
      - db

# Volume para garantir que os dados do banco não sumam ao desligar o container
volumes:
  postgres_data: